package com.rooptech.bankingapp.card.controller;

import com.rooptech.bankingapp.card.dto.CardRequestDto;
import com.rooptech.bankingapp.card.dto.CardResponseDto;
import com.rooptech.bankingapp.card.dto.CardUpdateRequestDto;
import com.rooptech.bankingapp.card.service.CardService;
import com.rooptech.bankingapp.common.ErrorResponseDto;
import com.rooptech.bankingapp.common.ResponseDto;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Positive;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
@Tag(
        name = "Cards",
        description = "APIs for creating, retrieving, updating and deleting customer cards"
)
@RestController
@RequiredArgsConstructor
@RequestMapping(path = "cards/api", produces = MediaType.APPLICATION_JSON_VALUE)
@Validated
@SecurityRequirement(name = "bearerAuth")
public class CardController {
    private final CardService cardService;

    @Operation(
            summary = "Create a new card",
            description = """
                Creates a new card for an existing bank account.
                The card number, issue date, expiry date, card status and
                default card limit are generated by the system.
                """
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "201",
                    description = "Card created successfully",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Success Response",
                                    value = """
                                        {
                                          "statusCode": "CREATED",
                                          "statusMessage": "card created successfully"
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "400",
                    description = "Invalid card request data",
                    content = @Content(
                            mediaType = "application/json",
                            examples = @ExampleObject(
                                    name = "Validation Error",
                                    value = """
                                        {
                                          "accountId": "Account ID must be positive",
                                          "cardType": "Card type is required"
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "404",
                    description = "Account not found",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ErrorResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Account Not Found",
                                    value = """
                                        {
                                          "apiPath": "/cards/api",
                                          "errorTime": "2026-09-28T15:30:00",
                                          "errorCode": "404 NOT_FOUND",
                                          "errorMessage": "Account not found"
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "409",
                    description = "Card of the same type already exists for the account",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ErrorResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Card Already Exists",
                                    value = """
                                        {
                                          "apiPath": "/cards/api",
                                          "errorTime": "2026-09-28T15:30:00",
                                          "errorCode": "409 CONFLICT",
                                          "errorMessage": "A CREDIT card already exists for this account"
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "500",
                    description = "Internal server error",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ErrorResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Internal Server Error",
                                    value = """
                                        {
                                          "apiPath": "/cards/api",
                                          "errorTime": "2026-09-28T15:30:00",
                                          "errorCode": "500 INTERNAL_SERVER_ERROR",
                                          "errorMessage": "Unexpected internal server error"
                                        }
                                        """
                            )
                    )
            )
    })
    @PostMapping
    public ResponseEntity<ResponseDto> createCard(@Valid
                                                      @RequestBody
                                                      CardRequestDto cardRequestDto){
        cardService.createCard(cardRequestDto);
        return ResponseEntity.status(HttpStatus.CREATED)
                .body(new ResponseDto(HttpStatus.CREATED,
                        "card created successfully"));
    }

    @Operation(
            summary = "Get card details",
            description = """
                Retrieves card details using the card ID and the
                associated bank account ID.
                """
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "Card details retrieved successfully",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = CardResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Card Details",
                                    value = """
                                        {
                                          "cardId": 101,
                                          "cardNumber": "1234567890123456",
                                          "cardIssuedAt": "2026-09-28",
                                          "expiryDate": "2029-09-28",
                                          "cardStatus": "ACTIVE",
                                          "cardLimit": 10000.00,
                                          "cardType": "CREDIT",
                                          "accountId": 1001
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "400",
                    description = "Card ID or account ID must be positive",
                    content = @Content(
                            mediaType = "application/json",
                            examples = @ExampleObject(
                                    name = "Validation Error",
                                    value = """
                                        {
                                          "cardId": "Card ID must be positive",
                                          "accountId": "Account ID must be positive"
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "404",
                    description = "Card not found for the specified account",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ErrorResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Card Not Found",
                                    value = """
                                        {
                                          "apiPath": "/cards/api/accounts/1001/cards/101",
                                          "errorTime": "2026-09-28T15:30:00",
                                          "errorCode": "404 NOT_FOUND",
                                          "errorMessage": "Card not found"
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "500",
                    description = "Internal server error",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ErrorResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Internal Server Error",
                                    value = """
                                        {
                                          "apiPath": "/cards/api/accounts/1001/cards/101",
                                          "errorTime": "2026-09-28T15:30:00",
                                          "errorCode": "500 INTERNAL_SERVER_ERROR",
                                          "errorMessage": "Unexpected internal server error"
                                        }
                                        """
                            )
                    )
            )
    })
    @GetMapping("/accounts/{accountId}/cards/{cardId}")
    public ResponseEntity<CardResponseDto> getCard(

            @PathVariable
            @Positive(message = "Account ID must be positive")
            Long accountId,
            @PathVariable
            @Positive(message = "Card ID must be positive")
            Long cardId
    ){
        return ResponseEntity.status(HttpStatus.OK)
                .body(cardService.getCard( accountId,cardId));
    }
    @Operation(
            summary = "Update card details",
            description = """
                Updates the status and card limit of an existing card
                associated with the specified bank account.
                """
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "Card details updated successfully",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Success Response",
                                    value = """
                                        {
                                          "statusCode": "OK",
                                          "statusMessage": "card updated successfully"
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "400",
                    description = "Invalid card update request",
                    content = @Content(
                            mediaType = "application/json",
                            examples = @ExampleObject(
                                    name = "Validation Error",
                                    value = """
                                        {
                                          "cardLimit": "Card limit must be positive"
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "404",
                    description = "Card not found for the specified account",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ErrorResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Card Not Found",
                                    value = """
                                        {
                                          "apiPath": "/cards/api/accounts/1001/cards/101",
                                          "errorTime": "2026-09-28T15:30:00",
                                          "errorCode": "404 NOT_FOUND",
                                          "errorMessage": "Card not found"
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "500",
                    description = "Internal server error",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ErrorResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Internal Server Error",
                                    value = """
                                        {
                                          "apiPath": "/cards/api/accounts/1001/cards/101",
                                          "errorTime": "2026-09-28T15:30:00",
                                          "errorCode": "500 INTERNAL_SERVER_ERROR",
                                          "errorMessage": "Unexpected internal server error"
                                        }
                                        """
                            )
                    )
            )
    })
    @PutMapping("/accounts/{accountId}/cards/{cardId}")
    public ResponseEntity<ResponseDto> updateCard(
            @PathVariable
            @Positive(message = "Card ID must be positive")
            Long cardId,
            @PathVariable
            @Positive(message = "Account ID must be positive")
            Long accountId,
            @Valid
            @RequestBody CardUpdateRequestDto requestDto
    ){
            cardService.updateCard(accountId,cardId,requestDto);
        return ResponseEntity.status(HttpStatus.OK)
                .body(new ResponseDto(HttpStatus.OK,
                        "card updated successfully"));
    }
    @Operation(
            summary = "Delete a card",
            description = """
                Deletes the specified card associated with a bank account.
                """
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "Card deleted successfully",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Success Response",
                                    value = """
                                        {
                                          "statusCode": "OK",
                                          "statusMessage": "card deleted successfully"
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "400",
                    description = "Card ID or account ID must be positive",
                    content = @Content(
                            mediaType = "application/json",
                            examples = @ExampleObject(
                                    name = "Validation Error",
                                    value = """
                                        {
                                          "cardId": "Card ID must be positive",
                                          "accountId": "Account ID must be positive"
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "404",
                    description = "Card not found for the specified account",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ErrorResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Card Not Found",
                                    value = """
                                        {
                                          "apiPath": "/cards/api/accounts/1001/cards/101",
                                          "errorTime": "2026-09-28T15:30:00",
                                          "errorCode": "404 NOT_FOUND",
                                          "errorMessage": "Card not found"
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "500",
                    description = "Internal server error",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ErrorResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Internal Server Error",
                                    value = """
                                        {
                                          "apiPath": "/cards/api/accounts/1001/cards/101",
                                          "errorTime": "2026-09-28T15:30:00",
                                          "errorCode": "500 INTERNAL_SERVER_ERROR",
                                          "errorMessage": "Unexpected internal server error"
                                        }
                                        """
                            )
                    )
            )
    })
    @DeleteMapping("/accounts/{accountId}/cards/{cardId}")
    public ResponseEntity<ResponseDto> deleteCard(
            @PathVariable
            @Positive(message = "Card ID must be positive")
            Long cardId,

            @PathVariable
            @Positive(message = "Account ID must be positive")
            Long accountId
    ) {
        cardService.deleteCard(accountId, cardId);

        return ResponseEntity.status(HttpStatus.OK)
                .body(new ResponseDto(
                        HttpStatus.OK,
                        "card deleted successfully"
                ));
    }
}
