package com.rooptech.bankingapp.account.controller;
import com.rooptech.bankingapp.account.dto.CustomerRequestDto;
import com.rooptech.bankingapp.account.dto.CustomerResponseDto;
import com.rooptech.bankingapp.account.dto.CustomerUpdateRequestDto;
import com.rooptech.bankingapp.common.ErrorResponseDto;
import com.rooptech.bankingapp.common.ResponseDto;
import com.rooptech.bankingapp.account.service.AccountService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Pattern;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

@Tag(
        name = "Accounts",
        description = "APIs for managing customers and their linked bank accounts"
)
@RestController
@RequestMapping(value = "/accounts/api", produces = MediaType.APPLICATION_JSON_VALUE)
@RequiredArgsConstructor
@Validated
@SecurityRequirement(name = "bearerAuth")
public class AccountController {
    private final AccountService accountService;


    @Operation(
            summary = "Create customer and linked bank account",
            description = """
                    Creates a new customer and links a bank account to the customer.
                    The account number is generated by the system and the initial
                    account balance is set to zero.
                    """
    )


    @ApiResponses({
            @ApiResponse(
                    responseCode = "201",
                    description = "Customer and bank account created successfully",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Success Response",
                                    value = """
                                        {
                                          "statusCode": "CREATED",
                                          "statusMessage": "account created successfully"
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "400",
                    description = "Invalid request data",
                    content = @Content(
                            mediaType = "application/json",
                            examples = @ExampleObject(
                                    name = "Validation Error",
                                    value = """
                                        {
                                          "customerName": "Customer name is required",
                                          "email": "Email must be valid",
                                          "mobileNumber": "Mobile number must be a valid 10-digit Indian mobile number"
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "409",
                    description = "Customer already exists with the given mobile number",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ErrorResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Customer Already Exists",
                                    value = """
                                        {
                                          "apiPath": "/accounts/api",
                                          "errorTime": "2026-09-25T18:30:00",
                                          "errorCode": "409 CONFLICT",
                                          "errorMessage": "Customer already exists with the given mobile number"
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "500",
                    description = "Internal server error",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ErrorResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Internal Server Error",
                                    value = """
                                        {
                                          "apiPath": "/accounts/api",
                                          "errorTime": "2026-09-25T18:30:00",
                                          "errorCode": "500 INTERNAL_SERVER_ERROR",
                                          "errorMessage": "Unexpected internal server error"
                                        }
                                        """
                            )
                    )
            )
    })
    @PostMapping
    public ResponseEntity<ResponseDto> createCustomer(@Valid @RequestBody CustomerRequestDto requestDto){
        accountService.createAccount(requestDto);
        return new ResponseEntity<>(new ResponseDto(HttpStatus.CREATED,
                "account created successfully"), HttpStatus.CREATED);
    }

    @Operation(
            summary = "Get customer account details",
            description = """
                Retrieves customer and linked bank account details
                using the customer's registered mobile number.
                """
    )


    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "Customer account details retrieved successfully",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = CustomerResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Customer Account",
                                    value = """
                                        {
                                          "customerId": 101,
                                          "customerName": "Roop Bose",
                                          "email": "roop@example.com",
                                          "mobileNumber": "9521567626",
                                          "accountResponseDto": {
                                            "branch": "Mumbai Main Branch",
                                            "accountType": "SAVING",
                                            "accountNumber": 123456789012,
                                            "balance": 25000.50
                                          }
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "400",
                    description = "Invalid mobile number",
                    content = @Content(
                            mediaType = "application/json",
                            examples = @ExampleObject(
                                    name = "Validation Error",
                                    value = """
                                        {
                                          "mobileNumber": "Mobile number must be a valid 10-digit Indian mobile number"
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "404",
                    description = "Customer not found",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ErrorResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Customer Not Found",
                                    value = """
                                        {
                                          "apiPath": "/accounts/api/9521567626",
                                          "errorTime": "2026-09-25T18:30:00",
                                          "errorCode": "404 NOT_FOUND",
                                          "errorMessage": "Customer not found with mobileNumber : 9521567626"
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "500",
                    description = "Internal server error",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ErrorResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Internal Server Error",
                                    value = """
                                        {
                                          "apiPath": "/accounts/api/9521567626",
                                          "errorTime": "2026-09-25T18:30:00",
                                          "errorCode": "500 INTERNAL_SERVER_ERROR",
                                          "errorMessage": "Unexpected internal server error"
                                        }
                                        """
                            )
                    )
            )
    })
    @GetMapping("/{mobileNumber}")
    public ResponseEntity<CustomerResponseDto> getCustomer(
            @Parameter(
                    description = "Registered 10-digit Indian mobile number of the customer",
                    example = "9521567626",
                    required = true
            )
            @PathVariable
            @Pattern(
                    regexp = "^[6-9][0-9]{9}$",
                    message = "Mobile number must be a valid 10-digit Indian mobile number"
            )
            String mobileNumber){
          CustomerResponseDto customerResponseDto= accountService.getAccount(mobileNumber);
        return  ResponseEntity.status(HttpStatus.OK)
                .body(customerResponseDto);
    }

    @Operation(
            summary = "Update customer details",
            description = """
                Updates the name, email address and mobile number
                of an existing customer using the customer ID.
                """
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "Customer details updated successfully",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Success Response",
                                    value = """
                                        {
                                          "statusCode": "OK",
                                          "statusMessage": "customer updated successfully"
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "400",
                    description = "Invalid request data",
                    content = @Content(
                            mediaType = "application/json",
                            examples = @ExampleObject(
                                    name = "Validation Error",
                                    value = """
                                        {
                                          "email": "Email must be valid",
                                          "mobileNumber": "Mobile number must be a valid 10-digit Indian mobile number"
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "404",
                    description = "Customer not found",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ErrorResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Customer Not Found",
                                    value = """
                                        {
                                          "apiPath": "/accounts/api/101",
                                          "errorTime": "2026-09-25T18:30:00",
                                          "errorCode": "404 NOT_FOUND",
                                          "errorMessage": "Customer not found"
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "500",
                    description = "Internal server error",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ErrorResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Internal Server Error",
                                    value = """
                                        {
                                          "apiPath": "/accounts/api/101",
                                          "errorTime": "2026-09-25T18:30:00",
                                          "errorCode": "500 INTERNAL_SERVER_ERROR",
                                          "errorMessage": "Unexpected internal server error"
                                        }
                                        """
                            )
                    )
            )
    })


    @PutMapping("/{customerId}")
    public ResponseEntity<ResponseDto> updateCustomer(
            @Parameter(
                    description = "Unique ID of the customer",
                    example = "101",
                    required = true
            )
            @PathVariable Long customerId,
            @Valid @RequestBody CustomerUpdateRequestDto requestDto) {

        accountService.updateAccount(customerId, requestDto);

        return ResponseEntity.ok(
                new ResponseDto(
                        HttpStatus.OK,
                        "customer updated successfully"
                )
        );
    }

    @Operation(
            summary = "Delete customer account",
            description = """
                Deletes the customer associated with the specified
                mobile number from the banking system.
                """
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "Customer account deleted successfully",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Success Response",
                                    value = """
                                        {
                                          "statusCode": "OK",
                                          "statusMessage": "customer deleted successfully"
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "400",
                    description = "Invalid mobile number",
                    content = @Content(
                            mediaType = "application/json",
                            examples = @ExampleObject(
                                    name = "Validation Error",
                                    value = """
                                        {
                                          "mobileNumber": "Mobile number must be a valid 10-digit Indian mobile number"
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "404",
                    description = "Customer not found",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ErrorResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Customer Not Found",
                                    value = """
                                        {
                                          "apiPath": "/accounts/api/9521567626",
                                          "errorTime": "2026-09-25T18:30:00",
                                          "errorCode": "404 NOT_FOUND",
                                          "errorMessage": "Customer not found with mobileNumber : 9521567626"
                                        }
                                        """
                            )
                    )
            ),

            @ApiResponse(
                    responseCode = "500",
                    description = "Internal server error",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ErrorResponseDto.class),
                            examples = @ExampleObject(
                                    name = "Internal Server Error",
                                    value = """
                                        {
                                          "apiPath": "/accounts/api/9521567626",
                                          "errorTime": "2026-09-25T18:30:00",
                                          "errorCode": "500 INTERNAL_SERVER_ERROR",
                                          "errorMessage": "Unexpected internal server error"
                                        }
                                        """
                            )
                    )
            )
    })
   @DeleteMapping("/{mobileNumber}")
    public ResponseEntity<ResponseDto> deleteCustomer(
            @Parameter(
                    description = "Registered 10-digit Indian mobile number of the customer",
                    example = "9521567626",
                    required = true
            )
            @PathVariable
            @Pattern(
                    regexp = "^[6-9][0-9]{9}$",
                    message = "Mobile number must be a valid 10-digit Indian mobile number"
              )
                                                         String mobileNumber){
             accountService.deleteAccount(mobileNumber);
            return   ResponseEntity.status(HttpStatus.OK)
                    .body(new ResponseDto(HttpStatus.OK,
                            "customer deleted successfully"));
   }


}
